<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace GPBMetadata;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad6010a0a746573742e70726f746f120467727063221d0a0b5465737452" .
            "657175657374120e0a06747970656964180120012803225d0a0954657374" .
            "5265706c79122b0a0a6765746461746161727218012003280b32172e6772" .
            "70632e546573745265706c792e476574446174611a230a07476574446174" .
            "61120a0a026964180120012803120c0a046e616d65180220012809323c0a" .
            "09587565786954657374122f0a075361795465737412112e677270632e54" .
            "657374526571756573741a0f2e677270632e546573745265706c79220062" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

